[workspace]
members = [
    "askama_patched",
    "askama_patched_derive",
    "askama_patched_escape",
    "askama_patched_shared",
    "testing",
]

default-members = [
    "askama_patched",
    "askama_patched_derive",
    "askama_patched_escape",
    "askama_patched_shared",
    "testing",
]
