[workspace]
members = [
    "askama",
    "askama_derive",
    "askama_escape",
    "askama_shared",
    "testing",
]

default-members = [
    "askama",
    "askama_derive",
    "askama_escape",
    "askama_shared",
    "testing",
]
